/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fluxpbx.swig;

public class API {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected API(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(API obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fluxpbxJNI.delete_API(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public API(CoreSession s) {
    this(fluxpbxJNI.new_API(CoreSession.getCPtr(s), s), true);
  }

  public String execute(String command, String data) {
    return fluxpbxJNI.API_execute(swigCPtr, this, command, data);
  }

  public String executeString(String command) {
    return fluxpbxJNI.API_executeString(swigCPtr, this, command);
  }

  public String getTime() {
    return fluxpbxJNI.API_getTime(swigCPtr, this);
  }

}
