/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fluxpbx.swig;

public class CoreSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CoreSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CoreSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fluxpbxJNI.delete_CoreSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSession(SWIGTYPE_p_switch_core_session_t value) {
    fluxpbxJNI.CoreSession_session_set(swigCPtr, this, SWIGTYPE_p_switch_core_session_t.getCPtr(value));
  }

  public SWIGTYPE_p_switch_core_session_t getSession() {
    long cPtr = fluxpbxJNI.CoreSession_session_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_switch_core_session_t(cPtr, false);
  }

  public void setChannel(SWIGTYPE_p_switch_channel_t value) {
    fluxpbxJNI.CoreSession_channel_set(swigCPtr, this, SWIGTYPE_p_switch_channel_t.getCPtr(value));
  }

  public SWIGTYPE_p_switch_channel_t getChannel() {
    long cPtr = fluxpbxJNI.CoreSession_channel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_switch_channel_t(cPtr, false);
  }

  public void setFlags(long value) {
    fluxpbxJNI.CoreSession_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return fluxpbxJNI.CoreSession_flags_get(swigCPtr, this);
  }

  public void setAllocated(int value) {
    fluxpbxJNI.CoreSession_allocated_set(swigCPtr, this, value);
  }

  public int getAllocated() {
    return fluxpbxJNI.CoreSession_allocated_get(swigCPtr, this);
  }

  public void setCb_state(input_callback_state_t value) {
    fluxpbxJNI.CoreSession_cb_state_set(swigCPtr, this, input_callback_state_t.getCPtr(value), value);
  }

  public input_callback_state_t getCb_state() {
    long cPtr = fluxpbxJNI.CoreSession_cb_state_get(swigCPtr, this);
    return (cPtr == 0) ? null : new input_callback_state_t(cPtr, false);
  }

  public void setHook_state(SWIGTYPE_p_switch_channel_state_t value) {
    fluxpbxJNI.CoreSession_hook_state_set(swigCPtr, this, SWIGTYPE_p_switch_channel_state_t.getCPtr(value));
  }

  public SWIGTYPE_p_switch_channel_state_t getHook_state() {
    return new SWIGTYPE_p_switch_channel_state_t(fluxpbxJNI.CoreSession_hook_state_get(swigCPtr, this), true);
  }

  public void setCause(SWIGTYPE_p_switch_call_cause_t value) {
    fluxpbxJNI.CoreSession_cause_set(swigCPtr, this, SWIGTYPE_p_switch_call_cause_t.getCPtr(value));
  }

  public SWIGTYPE_p_switch_call_cause_t getCause() {
    return new SWIGTYPE_p_switch_call_cause_t(fluxpbxJNI.CoreSession_cause_get(swigCPtr, this), true);
  }

  public void setUuid(String value) {
    fluxpbxJNI.CoreSession_uuid_set(swigCPtr, this, value);
  }

  public String getUuid() {
    return fluxpbxJNI.CoreSession_uuid_get(swigCPtr, this);
  }

  public void setTts_name(String value) {
    fluxpbxJNI.CoreSession_tts_name_set(swigCPtr, this, value);
  }

  public String getTts_name() {
    return fluxpbxJNI.CoreSession_tts_name_get(swigCPtr, this);
  }

  public void setVoice_name(String value) {
    fluxpbxJNI.CoreSession_voice_name_set(swigCPtr, this, value);
  }

  public String getVoice_name() {
    return fluxpbxJNI.CoreSession_voice_name_get(swigCPtr, this);
  }

  public int insertFile(String file, String insert_file, int sample_point) {
    return fluxpbxJNI.CoreSession_insertFile(swigCPtr, this, file, insert_file, sample_point);
  }

  public int answer() {
    return fluxpbxJNI.CoreSession_answer(swigCPtr, this);
  }

  public int print(String txt) {
    return fluxpbxJNI.CoreSession_print(swigCPtr, this, txt);
  }

  public int preAnswer() {
    return fluxpbxJNI.CoreSession_preAnswer(swigCPtr, this);
  }

  public void hangup(String cause) {
    fluxpbxJNI.CoreSession_hangup(swigCPtr, this, cause);
  }

  public void hangupState() {
    fluxpbxJNI.CoreSession_hangupState(swigCPtr, this);
  }

  public void setVariable(String var, String val) {
    fluxpbxJNI.CoreSession_setVariable(swigCPtr, this, var, val);
  }

  public void setPrivate(String var, SWIGTYPE_p_void val) {
    fluxpbxJNI.CoreSession_setPrivate(swigCPtr, this, var, SWIGTYPE_p_void.getCPtr(val));
  }

  public SWIGTYPE_p_void getPrivate(String var) {
    long cPtr = fluxpbxJNI.CoreSession_getPrivate(swigCPtr, this, var);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public String getVariable(String var) {
    return fluxpbxJNI.CoreSession_getVariable(swigCPtr, this, var);
  }

  public SWIGTYPE_p_switch_status_t process_callback_result(String result) {
    return new SWIGTYPE_p_switch_status_t(fluxpbxJNI.CoreSession_process_callback_result(swigCPtr, this, result), true);
  }

  public void say(String tosay, String module_name, String say_type, String say_method, String say_gender) {
    fluxpbxJNI.CoreSession_say(swigCPtr, this, tosay, module_name, say_type, say_method, say_gender);
  }

  public void sayPhrase(String phrase_name, String phrase_data, String phrase_lang) {
    fluxpbxJNI.CoreSession_sayPhrase(swigCPtr, this, phrase_name, phrase_data, phrase_lang);
  }

  public String hangupCause() {
    return fluxpbxJNI.CoreSession_hangupCause(swigCPtr, this);
  }

  public String getState() {
    return fluxpbxJNI.CoreSession_getState(swigCPtr, this);
  }

  public int recordFile(String file_name, int time_limit, int silence_threshold, int silence_hits) {
    return fluxpbxJNI.CoreSession_recordFile(swigCPtr, this, file_name, time_limit, silence_threshold, silence_hits);
  }

  protected int originate(CoreSession a_leg_session, String dest, int timeout, SWIGTYPE_p_switch_state_handler_table_t handlers) {
    return fluxpbxJNI.CoreSession_originate(swigCPtr, this, CoreSession.getCPtr(a_leg_session), a_leg_session, dest, timeout, SWIGTYPE_p_switch_state_handler_table_t.getCPtr(handlers));
  }

  public void destroy() {
    fluxpbxJNI.CoreSession_destroy(swigCPtr, this);
  }

  public void setDTMFCallback(SWIGTYPE_p_void cbfunc, String funcargs) {
    fluxpbxJNI.CoreSession_setDTMFCallback(swigCPtr, this, SWIGTYPE_p_void.getCPtr(cbfunc), funcargs);
  }

  public int speak(String text) {
    return fluxpbxJNI.CoreSession_speak(swigCPtr, this, text);
  }

  public void set_tts_parms(String tts_name, String voice_name) {
    fluxpbxJNI.CoreSession_set_tts_parms(swigCPtr, this, tts_name, voice_name);
  }

  public void set_tts_params(String tts_name, String voice_name) {
    fluxpbxJNI.CoreSession_set_tts_params(swigCPtr, this, tts_name, voice_name);
  }

  public int collectDigits(int abs_timeout) {
    return fluxpbxJNI.CoreSession_collectDigits__SWIG_0(swigCPtr, this, abs_timeout);
  }

  public int collectDigits(int digit_timeout, int abs_timeout) {
    return fluxpbxJNI.CoreSession_collectDigits__SWIG_1(swigCPtr, this, digit_timeout, abs_timeout);
  }

  public String getDigits(int maxdigits, String terminators, int timeout) {
    return fluxpbxJNI.CoreSession_getDigits__SWIG_0(swigCPtr, this, maxdigits, terminators, timeout);
  }

  public String getDigits(int maxdigits, String terminators, int timeout, int interdigit) {
    return fluxpbxJNI.CoreSession_getDigits__SWIG_1(swigCPtr, this, maxdigits, terminators, timeout, interdigit);
  }

  public String getDigits(int maxdigits, String terminators, int timeout, int interdigit, int abstimeout) {
    return fluxpbxJNI.CoreSession_getDigits__SWIG_2(swigCPtr, this, maxdigits, terminators, timeout, interdigit, abstimeout);
  }

  public int transfer(String extension, String dialplan, String context) {
    return fluxpbxJNI.CoreSession_transfer(swigCPtr, this, extension, dialplan, context);
  }

  public String read(int min_digits, int max_digits, String prompt_audio_file, int timeout, String valid_terminators, int digit_timeout) {
    return fluxpbxJNI.CoreSession_read(swigCPtr, this, min_digits, max_digits, prompt_audio_file, timeout, valid_terminators, digit_timeout);
  }

  public void detectSpeech(String arg0, String arg1, String arg2, String arg3) {
    fluxpbxJNI.CoreSession_detectSpeech(swigCPtr, this, arg0, arg1, arg2, arg3);
  }

  public String playAndGetDigits(int min_digits, int max_digits, int max_tries, int timeout, String terminators, String audio_files, String bad_input_audio_files, String digits_regex, String var_name, int digit_timeout, String transfer_on_failure) {
    return fluxpbxJNI.CoreSession_playAndGetDigits(swigCPtr, this, min_digits, max_digits, max_tries, timeout, terminators, audio_files, bad_input_audio_files, digits_regex, var_name, digit_timeout, transfer_on_failure);
  }

  public String playAndDetectSpeech(String file, String engine, String grammar) {
    return fluxpbxJNI.CoreSession_playAndDetectSpeech(swigCPtr, this, file, engine, grammar);
  }

  public int streamFile(String file, int starting_sample_count) {
    return fluxpbxJNI.CoreSession_streamFile(swigCPtr, this, file, starting_sample_count);
  }

  public int sleep(int ms, int sync) {
    return fluxpbxJNI.CoreSession_sleep(swigCPtr, this, ms, sync);
  }

  public int flushEvents() {
    return fluxpbxJNI.CoreSession_flushEvents(swigCPtr, this);
  }

  public int flushDigits() {
    return fluxpbxJNI.CoreSession_flushDigits(swigCPtr, this);
  }

  public int setAutoHangup(boolean val) {
    return fluxpbxJNI.CoreSession_setAutoHangup(swigCPtr, this, val);
  }

  public void setHangupHook(SWIGTYPE_p_void hangup_func) {
    fluxpbxJNI.CoreSession_setHangupHook(swigCPtr, this, SWIGTYPE_p_void.getCPtr(hangup_func));
  }

  public boolean ready() {
    return fluxpbxJNI.CoreSession_ready(swigCPtr, this);
  }

  public boolean bridged() {
    return fluxpbxJNI.CoreSession_bridged(swigCPtr, this);
  }

  public boolean answered() {
    return fluxpbxJNI.CoreSession_answered(swigCPtr, this);
  }

  public boolean mediaReady() {
    return fluxpbxJNI.CoreSession_mediaReady(swigCPtr, this);
  }

  public void waitForAnswer(CoreSession calling_session) {
    fluxpbxJNI.CoreSession_waitForAnswer(swigCPtr, this, CoreSession.getCPtr(calling_session), calling_session);
  }

  public void execute(String app, String data) {
    fluxpbxJNI.CoreSession_execute(swigCPtr, this, app, data);
  }

  public void sendEvent(Event sendME) {
    fluxpbxJNI.CoreSession_sendEvent(swigCPtr, this, Event.getCPtr(sendME), sendME);
  }

  public void setEventData(Event e) {
    fluxpbxJNI.CoreSession_setEventData(swigCPtr, this, Event.getCPtr(e), e);
  }

  public String getXMLCDR() {
    return fluxpbxJNI.CoreSession_getXMLCDR(swigCPtr, this);
  }

  public boolean begin_allow_threads() {
    return fluxpbxJNI.CoreSession_begin_allow_threads(swigCPtr, this);
  }

  public boolean end_allow_threads() {
    return fluxpbxJNI.CoreSession_end_allow_threads(swigCPtr, this);
  }

  public String get_uuid() {
    return fluxpbxJNI.CoreSession_get_uuid(swigCPtr, this);
  }

  public SWIGTYPE_p_switch_input_args_t get_cb_args() {
    return new SWIGTYPE_p_switch_input_args_t(fluxpbxJNI.CoreSession_get_cb_args(swigCPtr, this), false);
  }

  public void check_hangup_hook() {
    fluxpbxJNI.CoreSession_check_hangup_hook(swigCPtr, this);
  }

  public SWIGTYPE_p_switch_status_t run_dtmf_callback(SWIGTYPE_p_void input, SWIGTYPE_p_switch_input_type_t itype) {
    return new SWIGTYPE_p_switch_status_t(fluxpbxJNI.CoreSession_run_dtmf_callback(swigCPtr, this, SWIGTYPE_p_void.getCPtr(input), SWIGTYPE_p_switch_input_type_t.getCPtr(itype)), true);
  }

  public void consoleLog(String level_str, String msg) {
    fluxpbxJNI.CoreSession_consoleLog(swigCPtr, this, level_str, msg);
  }

  public void consoleLog2(String level_str, String file, String func, int line, String msg) {
    fluxpbxJNI.CoreSession_consoleLog2(swigCPtr, this, level_str, file, func, line, msg);
  }

}
