/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fluxpbx.swig;

public class Event {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fluxpbxJNI.delete_Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEvent(SWIGTYPE_p_switch_event_t value) {
    fluxpbxJNI.Event_event_set(swigCPtr, this, SWIGTYPE_p_switch_event_t.getCPtr(value));
  }

  public SWIGTYPE_p_switch_event_t getEvent() {
    long cPtr = fluxpbxJNI.Event_event_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_switch_event_t(cPtr, false);
  }

  public void setSerialized_string(String value) {
    fluxpbxJNI.Event_serialized_string_set(swigCPtr, this, value);
  }

  public String getSerialized_string() {
    return fluxpbxJNI.Event_serialized_string_get(swigCPtr, this);
  }

  public void setMine(int value) {
    fluxpbxJNI.Event_mine_set(swigCPtr, this, value);
  }

  public int getMine() {
    return fluxpbxJNI.Event_mine_get(swigCPtr, this);
  }

  public Event(String type, String subclass_name) {
    this(fluxpbxJNI.new_Event__SWIG_0(type, subclass_name), true);
  }

  public Event(SWIGTYPE_p_switch_event_t wrap_me, int free_me) {
    this(fluxpbxJNI.new_Event__SWIG_1(SWIGTYPE_p_switch_event_t.getCPtr(wrap_me), free_me), true);
  }

  public int chat_execute(String app, String data) {
    return fluxpbxJNI.Event_chat_execute(swigCPtr, this, app, data);
  }

  public int chat_send(String dest_proto) {
    return fluxpbxJNI.Event_chat_send(swigCPtr, this, dest_proto);
  }

  public String serialize(String format) {
    return fluxpbxJNI.Event_serialize(swigCPtr, this, format);
  }

  public boolean setPriority(SWIGTYPE_p_switch_priority_t priority) {
    return fluxpbxJNI.Event_setPriority(swigCPtr, this, SWIGTYPE_p_switch_priority_t.getCPtr(priority));
  }

  public String getHeader(String header_name) {
    return fluxpbxJNI.Event_getHeader(swigCPtr, this, header_name);
  }

  public String getBody() {
    return fluxpbxJNI.Event_getBody(swigCPtr, this);
  }

  public String getType() {
    return fluxpbxJNI.Event_getType(swigCPtr, this);
  }

  public boolean addBody(String value) {
    return fluxpbxJNI.Event_addBody(swigCPtr, this, value);
  }

  public boolean addHeader(String header_name, String value) {
    return fluxpbxJNI.Event_addHeader(swigCPtr, this, header_name, value);
  }

  public boolean delHeader(String header_name) {
    return fluxpbxJNI.Event_delHeader(swigCPtr, this, header_name);
  }

  public boolean fire() {
    return fluxpbxJNI.Event_fire(swigCPtr, this);
  }

  public boolean merge(Event to_merge) {
    return fluxpbxJNI.Event_merge(swigCPtr, this, Event.getCPtr(to_merge), to_merge);
  }

}
